version: 3

server: https://app.fossa.com

project:
  id: github.com/auth0-lab/fga-dotnet-sdk
  name: github.com/auth0-lab/fga-dotnet-sdk
  link: fga.dev
  url: github.com/auth0-lab/fga-dotnet-sdk

paths:
  only:
    - ./src/Auth0.Fga
  exclude:
    - ./src/Auth0.Fga.Test